from __future__ import annotations

import json
import logging
import re
from pathlib import Path

from issue_agent.agent.agent import CodingAgent
from issue_agent.config import AppConfig
from issue_agent.environment.base import Environment
from issue_agent.environment.factory import create_environment
from issue_agent.github.client import GitHubClient
from issue_agent.github.gitops import WorkspaceGit
from issue_agent.github.models import GitHubIssue, PullRequestDraft
from issue_agent.models.openai_model import OpenAIModel
from issue_agent.tools.filesystem import ListDirTool, ReadFileTool, WriteFileTool
from issue_agent.tools.git import GitDiffTool, GitStatusTool
from issue_agent.tools.registry import ToolRegistry
from issue_agent.tools.search import SearchTool
from issue_agent.tools.testing import RunTestsTool

logger = logging.getLogger(__name__)

_PR_AI_NOTE = "NOTE: this PR and everything within this PR is generated by AI"


def build_agent(
    workspace: Path,
    config: AppConfig,
    environment: Environment | None = None,
) -> tuple[CodingAgent, Environment]:
    env = environment or create_environment(workspace, config)
    tools = ToolRegistry()
    builders = {
        "filesystem": lambda: [
            ListDirTool(env),
            ReadFileTool(env),
            WriteFileTool(env),
        ],
        "search": lambda: [SearchTool(env)],
        "testing": lambda: [
            RunTestsTool(env, max_test_runs=config.limits.max_test_runs),
        ],
        "git": lambda: [GitStatusTool(env), GitDiffTool(env)],
    }
    selected = config.tools or ("filesystem", "search", "testing", "git")
    for name in selected:
        builder = builders.get(name)
        if builder is None:
            raise ValueError(f"Unknown tool group in config: {name}")
        for tool in builder():
            tools.register(tool)

    agent = CodingAgent(
        model=OpenAIModel(config.model_name),
        tools=tools,
        max_steps=config.max_steps,
        trajectory_dir=config.trajectory_dir,
    )
    return agent, env


class AgentRunner:
    """CLI orchestration: fetch → clone → branch → agent → commit → push → PR.

    With docker enabled, clone/agent tools/commit/push/PR all run inside the
    container via the Environment.
    """

    def __init__(
        self,
        config: AppConfig,
        github: GitHubClient | None = None,
    ):
        self.config = config
        self.github = github or GitHubClient()

    def run(self, repo: str, issue: str | int) -> str:
        gh_issue = self.github.get_issue(repo, issue)
        agent_name = self.config.agent_name(
            owner=gh_issue.owner,
            repo=gh_issue.repo,
            issue=gh_issue.number,
        )
        logger.info(
            "Fetched %s/%s#%s: %s",
            gh_issue.owner,
            gh_issue.repo,
            gh_issue.number,
            gh_issue.title,
        )
        logger.info("Agent identity: %s", agent_name)
        logger.info("Environment: %s", self.config.environment_type)

        workspace = (
            self.config.workspace_root / f"{gh_issue.owner}__{gh_issue.repo}"
        )
        workspace.mkdir(parents=True, exist_ok=True)

        environment = create_environment(
            workspace,
            self.config,
            github_token=self.github.token,
        )
        environment.start()
        git = WorkspaceGit(
            environment,
            self.github,
            gitignore_entries=self.config.gitignore_entries,
        )
        try:
            git.ensure_repo(repo)
            base_branch = git.prepare_workspace(gh_issue.owner, gh_issue.repo)
            logger.info("Workspace ready at %s (base=%s)", workspace, base_branch)

            branch = self.config.branch_name(gh_issue.number, gh_issue.title)
            git.create_branch(branch)
            logger.info("Created branch %s", branch)

            agent, _ = build_agent(
                workspace=workspace,
                config=self.config,
                environment=environment,
            )
            answer = agent.run(gh_issue.as_task())

            if not git.has_changes():
                logger.info("No local changes; skipping commit/PR")
                return answer

            draft = self._parse_pr_draft(answer, gh_issue)
            logger.info("Commit message: %s", draft.commit_message)
            logger.info("PR title: %s", draft.title)

            git.commit(
                draft.commit_message,
                author_name=agent_name,
                author_email=f"{agent_name}@users.noreply.github.com",
            )
            logger.info("Committed as %s", agent_name)
            git.push(gh_issue.owner, gh_issue.repo, branch)
            pr_url = git.create_pull_request(
                gh_issue.owner,
                gh_issue.repo,
                title=draft.title,
                body=self._with_ai_note(draft.body),
                head=branch,
                base=base_branch,
            )
            logger.info("Opened PR: %s", pr_url)
            return f"{answer}\n\nPull request: {pr_url}"
        finally:
            environment.cleanup()

    @staticmethod
    def _with_ai_note(body: str) -> str:
        text = body.rstrip()
        if _PR_AI_NOTE in text:
            return text + "\n"
        return f"{text}\n\n{_PR_AI_NOTE}\n"
        
    @staticmethod
    def _parse_pr_draft(text: str, issue: GitHubIssue) -> PullRequestDraft:
        match = re.search(r"\{.*\}", text, flags=re.DOTALL)
        if match:
            try:
                data = json.loads(match.group(0))
                commit_message = str(data.get("commit_message") or "").strip()
                title = str(data.get("pr_title") or "").strip()
                body = str(data.get("pr_body") or "").strip()
                if commit_message and title and body:
                    if f"#{issue.number}" not in body:
                        body = f"{body.rstrip()}\n\nFixes #{issue.number}"
                    return PullRequestDraft(
                        commit_message=commit_message,
                        title=title,
                        body=body,
                    )
            except json.JSONDecodeError:
                pass

        logger.warning(
            "Agent final response missing PR JSON; using fallback metadata"
        )
        return PullRequestDraft(
            commit_message=f"Fix issue #{issue.number}: {issue.title}",
            title=f"Fix #{issue.number}: {issue.title}",
            body=(
                f"Automated fix for #{issue.number}.\n\n"
                f"Fixes #{issue.number}"
            ),
        )
